export const tasks = [
  {
    customerId: 1,
    customerName: "Max Mustermann",
    customerAddress: "Werslerstr. 49, 44675 Verl",
    pharmacy: "Hauptweg Apotheke",
    openAmount: 8.5,
    taskType: "Delivery",
  },
  {
    customerId: 2,
    customerName: "Cherry Cole",
    customerAddress: "Quickstr. 9, 11324 Kromberg",
    pharmacy: "Mims Apotheke",
    openAmount: 18.5,
    taskType: "Delivery",
  },
  {
    customerId: 3,
    customerName: "Paul Wims",
    customerAddress: "Pluminweg. 12, 22365 Munich",
    pharmacy: "Kromacherstr. Apotheke",
    openAmount: 0,
    taskType: "Delivery",
  },
  {
    customerId: 4,
    customerName: "Tom Pieper",
    customerAddress: "Piepertweg. 4, 33578 Barlin",
    pharmacy: "Apotheke in der Stadt",
    openAmount: 0,
    taskType: "Delivery",
  },
  {
    customerId: 5,
    customerName: "Maya King",
    customerAddress: "Stephensweg. 2, 76876 Paradis",
    pharmacy: "Nasshorn Apotheke",
    openAmount: 3.5,
    taskType: "Delivery",
  },
];
